### ISSUE TITLE
Does type2-runtime support armv6l?

### ISSUE THREAD

**Issue by mediocregopher** [AppImage/type2-runtime#112]
Hi, I tried to build an AppImage with `ARCH=armhf` using appimagetool, but I receive a `Segmentation Fault` when running it on my RPI 1B which is `armv6l`. From digging around it looks like the runtime is being built using [armv7](https://github.com/AppImage/type2-runtime/blob/81de3e127a1acc40cce58584609ff07c2fdc338d/scripts/docker/create-build-container.sh#L21) for the `armhf` target.

My two questions about this are: am I correct that `armv6l` isn't currently supported? And if so, are there any plans to support it in the future, or is there some technical reason it's not possible?

Thanks!

**Comment by probonopd** [comment]
Thanks @mediocregopher. That's not intentional. Let's try whether the pull request above can fix it.

**Comment by mediocregopher** [comment]
@probonopd I tested with the armhf runtime in the PR and it worked perfectly :+1: :rocket:  From what I understand that should be backwards compatible with armv7, but I don't have any devices handy to confirm that with, so might be good to do that if possible before merging.

**Comment by TheAssassin** [comment]
ARMv6 hasn't been supported in many(!) years. I'm not even sure that the compiler produces an ARMv6 compatible binary when run as shown in #113. @mediocregopher please try the runtime binary from there and comment on the PR.

**Comment by mediocregopher** [comment]
Latest CI build is working great for me, thank you both!
