### ISSUE TITLE
-Wint-conversion when compiling runtime.c

### ISSUE THREAD

**Issue by danpla** [AppImage/type2-runtime#19]
Building the code at c9553b05938b22849ac3255ac923bf8e775ce539 gives:

```sh
runtime.c: In function 'fusefs_main':
runtime.c:905:27: warning: initialization of 'long unsigned int' from 'char *' makes integer from pointer without a cast [-Wint-conversion]
  905 |             {"fsname=%s", "squashfuse", 0},
      |                           ^~~~~~~~~~~~
runtime.c:905:27: note: (near initialization for 'fuse_opts[2].offset')
runtime.c:906:28: warning: initialization of 'long unsigned int' from 'char *' makes integer from pointer without a cast [-Wint-conversion]
  906 |             {"subtype=%s", "squashfuse", 0},
```

**Comment by probonopd** [comment]
How are you building it? Seems to build fine in this project's CI pipeline.

**Comment by danpla** [comment]
I used the standard
```
export ARCHITECTURE=x86_64
./chroot_build.sh
```

But these warnings are also visible in CI logs. Just make sure you select "View raw logs" from the gear menu before searching with Ctrl+F (otherwise, GitHub will dynamically load only the visible parts of the log, breaking the search).

**Comment by TheAssassin** [comment]
This warning is not generated in our official build setup. Doesn't seem to be a problem any more, it seems. Closing therefore.
