### ISSUE TITLE
Make runtime debuggable

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/type2-runtime#25]
It would be really helpful if one was able to debug this runtime with a debugger. The easiest way to do so is to build with debug symbols and provide those in a separate file (`objcopy` can do this).

Some optimizations may have to be disabled for this to be actually useful, though. However, we'll have to try it first. Increasing the execution time by a few % shouldn't be a big deal, same goes for the actual binary size.

In any case, it should be possible to provide some debug symbols.

**Comment by probonopd** [comment]
I'd be all for a separate version for debugging reasons, but not to be shipped in production to end users by default.

**Comment by TheAssassin** [comment]
> not to be shipped in production to end users by default

Replacing a seemingly broken version with a working one is simple, but it does not reveal the actual problem that the user had. You must be able to debug the version in front of you.

> separate version for debugging reasons

Why have a separate version at all when you can combine the existing one with debug symbols you can download additionally? Again: the symbols would be in a _separate_ file.

**Comment by probonopd** [comment]
Is this roughly what you have in mind?

```
# Create example program
cat > example.c <<\EOF
#include <stdio.h>

int main() {
    printf("Hello, World!\n");
    return 0;
}
EOF

# Compile
gcc -g -o example example.c

# Use objcopy to extract the debug symbols into a separate file
objcopy --only-keep-debug example example.debug

# Strip the debug symbols from the original executable to reduce its size, while keeping the debug information in the separate file
objcopy --strip-debug example

# Compare to traditional stripping
cp example example.stripped
strip example.stripped 

# Compare sizes
ls -lh example example.debug example.stripped
17K  example
7.7K example.debug
15K example.stripped
```

**Comment by TheAssassin** [comment]
Reopening as the commit that was pushed by accident produces broken debug symbols.

```sh
> gdb runtime-x86_64 runtime-x86_64.debug
[...]
(No debugging symbols found in runtime-x86_64)
"/tmp/ramdisk/runtime-x86_64.debug" is not a core dump: file format not recognized
```

This is most likely related to the unfiltered stripping as this strips _everything_.
