### ISSUE TITLE
Public key is not uploaded properly

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/type2-runtime#30]
For some reason, the pubkey is not uploaded. We should debug this once #28 has been merged.

**Comment by probonopd** [comment]
...which just happened. Thanks @TheAssassin

**Comment by TheAssassin** [comment]
Quite simple: the sign step just never runs. Might be the condition to filter PRs, which I stole somewhere but never really tried like that. I'll have a look.

**Comment by TheAssassin** [comment]
Fixed by [47b6655](https://github.com/AppImage/type2-runtime/commit/47b665594856b4e8928f8932adcf6d13061d8c30).
