### ISSUE TITLE
Find fusermount on the $PATH

### ISSUE THREAD

**Issue by probonopd** [AppImage/type2-runtime#31]
We cannot rely on the compile-time `FUSERMOUNT_DIR` at build time but have to look at the `$PATH` on the target system at runtime, because distributions agree on nothing.

Use case:
* https://github.com/probonopd/go-appimage/issues/281

Essentially we need to reinstate `findBinaryOnPath` from https://github.com/AppImage/type2-runtime/pull/11/commits/f0e35b014bea9f7d704f7ac1977be90487cac595.

**Comment by TheAssassin** [comment]
Can't we send the required syscall(s) directly without requiring an external utility to be present on the system?

**Comment by probonopd** [comment]
Test case:
On NixOS, AppImages fail to find FUSE.

With `FUSERMOUNT_PROG=$(which fusermount) ./My.AppImage` it works nicely. So this is something we definitely need to fix in the AppImage type2-runtime. Apparently it doesn't search for `fusermount` on the `PATH` properly yet.
