### ISSUE TITLE
use writable overlays?

### ISSUE THREAD

**Issue by stsp** [AppImage/type2-runtime#39]
Hi, have the writable overlays been considered
for appimages? I am trying to package
the proprietary programs (a DOS programs
actually) that are not educated enough
to write to tmp dirs or alike.
I think fuse has fuse-overlayfs, so such
a feature is not going to be difficult to
implement?

**Comment by probonopd** [comment]
Hi @stsp

It's doable by putting fuse-overlayfs into the AppImage, and then invoking it from the `AppRun` script. 
See https://github.com/AppImage/AppImageKit/wiki/Bundling-Windows-applications#3-make-it-possible-to-use-a-read-only-wineprefix-1.

Such functionality goes into the AppImage payload, not into the runtime.

**Comment by stsp** [comment]
I actually thought your suggestion works...
But it appears not.
There is some problem, I think in fuse-overlayfs:
it makes only the dir writable, but all existing
files are still read-only, as strange as it may sound.
I filled this ticket:
https://github.com/containers/fuse-overlayfs/issues/428
It has a ready-to-use AppImage test-case within.
So if you can help, please join that ticket. :)

**Comment by probonopd** [comment]
Sounds like a bug to me.

**Comment by stsp** [comment]
Have you tried my reproducer?
Does it reproduce for you as well?

**Comment by probonopd** [comment]
Sorry, can't try to reproduce right now. Can you reproduce this in a simple test case that does not involve AppImage?

**Comment by stsp** [comment]
Ok, added a trivial test-case to the
aforementioned ticket.

**Comment by stsp** [comment]
And found the problem: the files are
not writable if in the lowerdir they belong
to another user.
