### ISSUE TITLE
Could not find section .digest_md5 in runtime

### ISSUE THREAD

**Issue by toasterofbread** [AppImage/type2-runtime#47]
My project's AppImage package task suddenly stopped working today, both locally and in my CI pipeline. Build [works](https://github.com/toasterofbread/spmp/actions/runs/10206602355/job/28239829670) when using a local runtime built on cc87adefa2ea5972c40d9f94f2f2578187096ccc.

Pipelines (both on the same commit, see the end of the `Build AppImage` step): 
- [Working](https://github.com/toasterofbread/spmp/actions/runs/10187600380/job/28182012895) (ran yesterday)
- [Failing](https://github.com/toasterofbread/spmp/actions/runs/10187713699/job/28237998752) (ran today)

Point of failure in logs:
```
Embedding ELF...
Marking the AppImage as executable...
Embedding MD5 digest
Platforms other than 32-bit/64-bit are currently not supported!Could not find section .digest_md5 in runtime
```

**Comment by TheAssassin** [comment]
What version of appimagetool are you using? The runtime appears to work in linuxdeploy's (and its Qt plugin's) CI pipelines just fine.

**Comment by toasterofbread** [comment]
Whatever the latest continuous release version is at the time of build, both locally and in CI.
```
    - name: Download appimagetool
      run: wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
```

The appimagetool on my NixOS system (not I use for builds, since I do that through Docker) still works though, even when explicitly supplying the latest runtime using `--runtime-file`. It's built on https://github.com/AppImage/AppImageKit/commit/8bbf694455d00f48d835f56afaa1dabcd9178ba6 (see the [package file](https://github.com/NixOS/nixpkgs/blob/084f6a3e260a9576c955137ff44b2e6d4fac6891/pkgs/tools/package-management/appimagekit/default.nix#L4)).

**Comment by toasterofbread** [comment]
The Nix package works even when building from the latest AppImageKit and squashfuse commits.

**Comment by probonopd** [comment]
Note that https://github.com/AppImage/appimagetool is a newer version thatn the soon-to-be retired codebase in AppImageKit.

**Comment by toasterofbread** [comment]
Seems to be [working again](https://github.com/toasterofbread/spmp/actions/runs/10187713699), thanks.
