### ISSUE TITLE
Something broke in the last 24 hours `terminate called after throwing an instance of 'appimage::update::AppImageError'`

### ISSUE THREAD

**Issue by Samueru-sama** [AppImage/type2-runtime#69]
Hello, I recently made this [PR](https://github.com/srevinsaju/Brave-AppImage/pull/11) and everything at the Brave appimage repo updating to use this appimagetool. 

I've noticed that when trying to use appimageupdatetool it is throwing an error, that's odd since when I made the changes it was working perfectly.

Thankfully the CI was setup to make builds several times a day, [so I can check where the error started](https://github.com/Samueru-sama/Brave-AppImage/releases)

* Build v1.70.74 made 2 days ago is [working fine](https://imgur.com/MGyGjSI)

* Build v1.70.75 made yesterday is working fine as well

* Build v1.70.76 made yesterday and all builds after [**have the problem**](https://imgur.com/a/waZGynO)

```
appimageupdatetool ./Brave-nightly-v1.70.76-x86_64.AppImage
terminate called after throwing an instance of 'appimage::update::AppImageError'
  what():  Unknown AppImage type or not an AppImage
zsh: IOT instruction  appimageupdatetool ./Brave-nightly-v1.70.76-x86_64.AppImage
```

[The build log says that everything went fine](https://github.com/Samueru-sama/Brave-AppImage/actions/runs/10384140457/job/28750579563#step:3:262)

The issue is very likely upstream since appimagetool uses the CI zsync instead of bundling one, but I thought I would let you know anyway.

**Comment by TheAssassin** [comment]
The magic bytes are not there for some reason. Only an `A` is set, not `AI\x02`.

**Comment by TheAssassin** [comment]
To be fair, `objcopy` is probably right here to eliminate the magic bytes. They're somewhat offending the ELF spec. We've known that for years. We need to change their location.

**Comment by Samueru-sama** [comment]
Thanks for fixing it asap @TheAssassin
