### ISSUE TITLE
Error when building with docker script (pull access denied)

### ISSUE THREAD

**Issue by andy5995** [AppImage/type2-runtime#74]
```
 => CACHED [6/6] RUN bash scripts/common/install-dependencies.sh                                                       0.0s
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load

 1 warning found (use docker --debug to expand):
 - InvalidDefaultArgInFrom: Default value for ARG ${docker_arch}/alpine:latest results in empty or invalid base image name (line 2)
Unable to find image 'amd64/type2-runtime-build:latest' locally
docker: Error response from daemon: pull access denied for amd64/type2-runtime-build, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

https://github.com/AppImage/type2-runtime/blob/01164bfcbc8dd2bd0d7e3706f97035108d6b91ba/BUILD.md?plain=1#L17

**Comment by andy5995** [comment]
Ok, silly of me not to have noticed that I needed the '--load' option. I added it to L41 of create_build_container.sh and it works now.

**Comment by TheAssassin** [comment]
We don't use Docker buildx and we also don't need to push the resulting image somewhere. The warning can stay in place, it's just that, a warning. This check you proposed is much more complexity than what we'd like to maintain. Plus the build works in all the test environments we use.

You have not laid out your use case or justified in _any_ way why this would be necessary in your specific environment. A simple log excerpt without any context, a link to a build log or any other information is not enough to open an issue let alone send a PR. All I can say is, it works for us, it works for our development workflow, and we cannot reproduce this issue in any way.

Please reopen with more information should the error persist. We've changed the scripting recently anyway, so this might be outdated already.

**Comment by andy5995** [comment]
I've found that buildx can be easily disabled by exporting `DOCKER_BUILDKIT=0` prior to using `docker build ...`, so in effect, adding '--load' isn't needed.

**Comment by probonopd** [comment]
According to https://docs.docker.com/build/buildkit/, "Buildx always uses BuildKit".
So since we have never tested our setup with Buildx nor BuildKit, poerhaps we should mention in the documentation not to use them.
